/**
 *  Mappu : yet another web gis (with social taste).
 *  Copyright (c) 2011 Umberto Nicoletti - umberto.nicoletti _at_ gmail.com, all rights reserved.
 *
 *  Licensed under the LGPL.
 */


SC.stringsFor('en', {
    "_appName" : "Comune di Mirano",
    "_layers" : "Layers",
    "_search" : "Search",
    "_pan"    : "Pan",
    "_area"   : "Area",
    "_length" : "Length",
    "_geotools" : "Geo Tools",
    "_explorer" : "Explore",
    "_reloadtags" : "Reload",
    "_rendertags" : "Render",
    "_property" : "Property",
    "_value"    : "Value",
    "_howtotypetags" : "Use a comma (,) to separate tags",
    "_save"   : "Save",
    "_addcomment_tip" : "Add a comment...",
    "_nosocial_expl" : "Select a result from the list above. If this message does not disappear then the selected feature is missing an ID property and therefore it is not possible add anything to it. Please ask your GIS administrator to consider adding an ID field to this layer.",
    "_links" : "Links",
    "_query_howto" : "Double click to choose one of the available queries",
    "_back" : "Back",
    "_run"  : "Run",
    "_streets_satellite" : "Streets Satellite",
    "_info" : "Info",
    "_opacity" : "Opacity:",
    "_intersection" : "Intersection",
    "_union" : "Union",
    "_area" : "Area",
    "_buffer5" : "Buffer 5m",
    "_buffer25" : "Buffer 25m",
    "_clear"  : "Clear",
    "_close"  : "Close",
    "_username" : "Username :",
    "_drop_here" : "Drop here",
    "_tags" : "Tags",
    "_comments" : "Comments",
    "_missing_params" : "Missing Parameters",
    "_select_features" : "Select features and drop them in the drop doxes before attempting a",
    "_op_failed" : "The requested operation failed",
    "_query_error_title" : "The server connection failed",
    "_query_error_detail" : "While connecting to the server the application received an error. HTTP error code (if available): ",
    "_starred" : "You starred this feature",
    "_not_starred" : "This feature has not been starred",
    "_no_info_avail" : "No additional information available",
    "_geotools_help" : "Identify features by clicking on the map, then drag them from the" +
        " list on the right to the placeholders above. Select an operation from the menu and then click 'OK' to execute it." +
        " Click on clear to remove the result from the map.",
    "_max_tags_title": "Please select at most %@ tags",
    "_max_tags_body": "Tag rendering is capped at %@ tags to avoid slowing down the browser too much while rendering.",
    "_clear_q": "Clear",
    "_tagexplorer_help": "Tick at most 4 tags then click the render button below to display them in the map.",
    "_print": "Printing",
    "_logout": "Logout",
    "_working_on_it": "The requested functionality is currently not yet available.",
    "_help": "Help",
    "_install_print_extension": "Install extension...",
    "_print_chrome_title" : "Please install extension to print with Google Chrome",
    "_print_chrome_body" : "Printing in Google Chrome is also supported through a custom made extension",
    "_print_mozilla_title" : "Please install an extension to print with Mozilla",
    "_print_mozilla_body" : "Printing in Mozilla is supported through one of the many available screenshot extensions.",
    "_msie_unsupported" : "You are using Internet Explorer",
    "_msie_unsupported_body" : "We are sorry, but despite out best efforts Internet Explorer is not currently completely supported by this application.\nYou can continue unsupported or upgrade to a supported browser.",
    "_msie_unsupported_caption" : "Supported browsers are: Google Chrome or Safari (recommended), any recent version of Firefox.",
    "_close": "Close",
    "_legend": "Legend",
    "_layerprops": "Properties",
    "_help_text" : "To be translated.",
    "_session_expired": "Session expired, please reload the page",
    "_session_expired_detail": "Your login session has expired. To continue using the application please reload the page and then login again.",
    "_settings": "Settings",
    "_filter_error": "Cannot apply filter",
    "_filter_error_body": "The layer you are trying to filter is probably a layer group, which are not, at this point, supported.",
    "_description:": "Description:",
    "_remove_filter": "Clear filter:",
    "_geocode": "Geocode",
    "_streetview": "Streetview",
    "_tip_at_startup": "Show tips at startup",
    "_usage_tip_title": "Did you know that ... ?",
    "_tips" : "Tips",
    "_next": "Next",
    "_loading": "Loading...",
    "_print_title": "Print options",
    "_comment": "Optional comment to be added on the print:",
    "_do_print": "Print",
    "_layer_pane_instructions":"Select a layer to get started",
    "_attributes": "Attributes",
    "_addcomment": "Add a comment",
    "_delcomment": "Delete selected comment",
    "_select_above": "Please select a result above",
    "_please_wait": "Please wait...",
    "_only_show_mine" : "Only show my tags",
    "_only_show_mine_tip" : "Tags are shared among all users",
    "_users": "Users",
    "_close": "Close",
    "_create": "New",
    "_changepwd": "Change password",
    "_Username:": "Username:",
    "_Enabled:": "Enabled:",
    "_password:": "Password:",
    "_passwordrepeat:": "Retype password:",
    "_please_select_an_item": "Please select an item from the list on the left",
    "_cancel": "Cancel",
    "_pwd_not_match": " Passwords don't match",
    "_user_exists": " User already exists",
    "_edit": "Edit",
    "_Title:": "Title:",
    "_Layer:": "Layer:",
    "_LayerGroup:": "Layer group:",
    "_Description:": "Description:",
    "_Url:": "URL:"
});
